<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.omardiaa</groupId>
    <artifactId>discord-html-transcript</artifactId>
    <version>0.1.0-beta.7</version>
  </parent>

  <artifactId>discord-html-transcript-core</artifactId>

  <packaging>jar</packaging>

  <name>discord-html-transcript-core</name>
  <url>https://github.com/omardiaadev/discord-html-transcript</url>

  <scm>
    <connection>scm:git:https://github.com/omardiaadev/discord-html-transcript.git</connection>
    <developerConnection>scm:git:https://github.com/omardiaadev/discord-html-transcript.git</developerConnection>
    <url>https://github.com/omardiaadev/discord-html-transcript</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>gg.jte</groupId>
      <artifactId>jte</artifactId>
    </dependency>

    <dependency>
      <groupId>tools.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>gg.jte</groupId>
        <artifactId>jte-maven-plugin</artifactId>
        <configuration>
          <sourceDirectory>${project.basedir}/src/main/resources/jte</sourceDirectory>
          <targetDirectory/>
          <binaryStaticContent>true</binaryStaticContent>
          <contentType>Html</contentType>
          <extensions>
            <extension>
              <className>gg.jte.nativeimage.NativeResourcesExtension</className>
            </extension>
          </extensions>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>gg.jte</groupId>
            <artifactId>jte-native-resources</artifactId>
            <version>${jte.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>copy-templates</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>update-css</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>initialize</phase>
            <configuration>
              <target>
                <concat destfile="${project.basedir}/src/main/resources/jte/style.jte">
                  <header>&lt;style&gt;${line.separator}</header>
                  <fileset file="${project.basedir}/src/main/resources/style.css"/>
                  <footer>&lt;/style&gt;</footer>
                </concat>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-classes</phase>
            <configuration>
              <outputDirectory>${project.build.outputDirectory}</outputDirectory>
              <resources>
                <resource>
                  <directory>${project.basedir}/target/generated-sources/jte</directory>
                  <includes>
                    <include>**/*.bin</include>
                    <include>META-INF/**/*</include>
                  </includes>
                  <filtering>false</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
