POST https://<DISCORD_TRANSCRIPT_HOST>:<DISCORD_TRANSCRIPT_PORT>/transcript
Server-Version: 0.1.0-beta.7
Authorization: Bearer <DISCORD_TRANSCRIPT_API_KEY>

# body
< payload.json

# response (overrides existing file)
>>! transcript.html

###

# @no-log
GET https://<DISCORD_TRANSCRIPT_HOST>:<DISCORD_TRANSCRIPT_PORT>/health
Server-Version: 0.1.0-beta.7
Authorization: Bearer <DISCORD_TRANSCRIPT_API_KEY>
